### ISSUE TITLE
[feature request] PGA language statistics

### ISSUE THREAD

**Issue by EgorBu** [src-d/datasets#110]
Hello,

it could be a useful feature to provide language statistics per repository -> so people will have more advanced options for filtering repositories.

Example:
Downloading of a repository with 1 line of JS code and 1000s in other languages could be not so useful for researchers who are focusing on JS.

**Comment by vmarkovtsev** [comment]
@EgorBu We already have the line info in the index file, WDYM?

**Comment by EgorBu** [comment]
I think at that time it was not included, but I don't remember all details right now
