### ISSUE TITLE
Download v2 repositories

### ISSUE THREAD

**Issue by jfontan** [src-d/datasets#117]
The download will use a new gluster volume that will be created by infrastructure. (src-d/infrastructure#585). Also all processes will run in a namespace called `pga`.

* [x] gluster volume ready src-d/infrastructure#585
* [x] create batch job that uses `pga-create` container to create the list of repositories. The list and other files will reside in the gluster volume.
* [x] check that the list is correct and compare with the previous one
* [x] rabbitmq and postgres ready src-d/infrastructure#584
* [x] start borges consumers pointing the pga gluster volume and rabbitmq + db servers
* [x] create borges jobs from the repository list
* [x] create a new borges dashboard that points to the pga database. The source can be found here: https://github.com/src-d/borges/blob/master/extra/grafana/dashboard.json

While the repositories are being downloaded check for possible problematic repositories.

* [ ] add job description to charts repository
* [ ] update documentation

**Comment by jfontan** [comment]
All repositories are now downloaded.

**Comment by jfontan** [comment]
We should add the job description and update the documentation before closing the issue.

**Comment by vmarkovtsev** [comment]
@jfontan I guess that this is done.
