### ISSUE TITLE
error when running `pga list`

### ISSUE THREAD

**Issue by ycaxgjd** [src-d/datasets#140]
Hey, I install __pga__ today then run `pga list`, but always get this error message:
```
could not open index file: could not copy to temporary file ~/.pga/latest.csv.gz.tmp: Get https://pga.sourced.tech/csv/latest.csv.gz: x509: certificate has expired or is not yet valid
```
WDYT?

**Comment by vmarkovtsev** [comment]
@rporres Looks like our SSL certificate has expired.

@ycaxgjd Thank you for noticing, we will fix this soon.

**Comment by meyskens** [comment]
We fixed the certificate, thanks for noticing!
