### ISSUE TITLE
Commit Messages folder is empty

### ISSUE THREAD

**Issue by akhvorov** [src-d/datasets#172]
I am trying to open and load the dataset with commit messages, but the folder on the "[Download link](https://drive.google.com/drive/folders/1Os5MKKdpNUsWUN_vrP23PjsLCq-VpIev)" is empty.

**Comment by EgorBu** [comment]
source{d} is :skull: , all related google cloud storage was removed :cry:

**Comment by akhvorov** [comment]
:(
