### ISSUE TITLE
Programming language Identifiers dataset link redirects to a broken link

### ISSUE THREAD

**Issue by pavinduLakshan** [src-d/datasets#174]
Programming language Identifiers dataset link directs me to a broken URL.    

https://github.com/src-d/datasets/tree/master/Identifiers -> 
https://drive.google.com/open?id=1wZR5zF1GL1fVcA1gZuAN_9rSLd5ssqKV

**Comment by indigoviolet** [comment]
@vmarkovtsev, any chance these can be updated?

**Comment by chandraauliatama** [comment]
Any update about new dataset link?
