### ISSUE TITLE
Make PGA downloader safe to cancel

### ISSUE THREAD

**Issue by smola** [src-d/datasets#39]
It's quite annoying to run PGA, cancel it with Control+C and get a lot of corrupted files (potentially one per thread). Ideally, recovering from this should be easier.

As a starting point, files could be downloaded to a temporary path and then renamed to the final one only if the download succeeded. Cleaning up these temporary files on Control+C would be a plus.

**Comment by campoy** [comment]
I see your concern, but I'm wondering whether simply adding the md5 validation is enough

Basically if you cancel a download you'll get corrupt (incomplete) files, but you can then simply run `pga get ...` again continue the download.

Do you think this is enough?

Alternatively I could implement the download to a temporary path, but this doesn't remove all issues as copying to hdfs for instance could fail too and end up with corrupted files.

**Comment by campoy** [comment]
Removing it from the `pga-release` milestone as I consider this to be an optional improvement rather than a requirement for the tool to be useful.

**Comment by smola** [comment]
@campoy I don't intend to resume the download, but to try pga with some subset. That is why I'm cancelling at some point arbitrarily. However, if I could run a command to verify md5 of already downloaded files and find the corrupted ones to remove them manually, that would be enough for me.

**Comment by campoy** [comment]
If you want to try pga with a subset of the data, wouldn't it make sense to specify which one?
I have tested the tool by downloading only my own repos, for instance `pga get -u /campoy/`

**Comment by smola** [comment]
Yes, actually that would work very well for my use case.
