### ISSUE TITLE
[Feature request] Add stars to index file

### ISSUE THREAD

**Issue by smacker** [src-d/datasets#43]
It would be super useful for experiments to be able to grep and download only repositories with more than N stars.

**Comment by vmarkovtsev** [comment]
Workaround:
```
multitool discover
multitool select
```
Those are for creating the dataset; effectively, produce the list of repo names filtered by several criteria.

**Comment by bzz** [comment]
Got the same feedback from the workshop participants who were exposed to PGA for the first time - people want to be able to order/filter by starts before downloading anything.

It would be nice to do that, without excessive use of network traffic, that I assume the proposed workaround would result in.
