### ISSUE TITLE
Critical VIP repositories missing in PGA

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/datasets#45]
```
MariaDB/server
tensorflow/tensorflow
python/cpython
rails/rails
django/django
```

**Comment by vmarkovtsev** [comment]
@campoy I learned how to add repos to PGA with the date reset to Feb 14th, so if you know any popular VIP repos >50 stars which are not included, please list them here.

**Comment by campoy** [comment]
I think the interesting question is why didn't those repos make it to pga originally?
Is there a bug on our side, or is the GitHub archive incomplete?

**Comment by vmarkovtsev** [comment]
Done

**Comment by vmarkovtsev** [comment]
@campoy Can you please test that nothing was broken.

**Comment by campoy** [comment]
Confirmed: I was able to download all of those repos using `pga`.
