### ISSUE TITLE
Logo for Public Git Archive

### ISSUE THREAD

**Issue by campoy** [src-d/datasets#55]
I created a pretty straight forward one as a placeholder

@ricardobaeta could you provide something better or approve this one?

<img width="1314" alt="pga" src="https://user-images.githubusercontent.com/2237452/39831029-06447210-5378-11e8-9bd9-353fb37a479a.png">

**Comment by ricardobaeta** [comment]
Hi @campoy!

I think for now you got something solid here, thank you :) I'll provide some mocuks for a new one on the week from the 28th till the 1th.

**Comment by smola** [comment]
Note that when using the git logo, attribution for the author and the license is required: https://git-scm.com/downloads/logos

**Comment by campoy** [comment]
Hey @ricardobaeta, any news on the logo?

**Comment by ricardobaeta** [comment]
Hey @campoy :) Hot off the press!

![image](https://user-images.githubusercontent.com/1746146/41632815-a880fc84-7433-11e8-9ddf-500d045d60d3.png)

**Comment by campoy** [comment]
I like it! I have only two suggestions:

1. could you make the yellow lines a bit darker? Right now the contrast with the white background makes them hard to see.

2. the straight lines on what I assume is a sphere break the illusion, maybe you could add some distortion to make them look more like the image below. That also applies to the other horizontal lines (green and purple branches)

![image](https://user-images.githubusercontent.com/2237452/41675220-f19ed402-7476-11e8-84fe-2db07c82ab04.png)

**Comment by ricardobaeta** [comment]
Hi Francesc!

The rings are really not to be seen so much :)

**Per your suggestions**

![logo-one](https://user-images.githubusercontent.com/1746146/41688928-03fabd72-74e6-11e8-9c45-84ffd0c25bd9.png)

**If you want to go crazy**

![logo-two](https://user-images.githubusercontent.com/1746146/41688940-159ebcfe-74e6-11e8-83ec-8f2fb04a1ce2.png)

**Comment by marnovo** [comment]
> I like it! I have only two suggestions:
> 
> 1. could you make the yellow lines a bit darker? Right now the contrast with the white background makes them hard to see.
> 
> 2. the straight lines on what I assume is a sphere break the illusion, maybe you could add some distortion to make them look more like the image below. That also applies to the other horizontal lines (green and purple branches)
> 
> ![image](https://user-images.githubusercontent.com/2237452/41675220-f19ed402-7476-11e8-84fe-2db07c82ab04.png)

1. Both the original and the updated version seem fine to me if the intent is leaving it subtle. The updated one with darker blue in the title is better for accessibility.

2. The one without the 3D distortion looks more vintage/flat, like we have on other design artifacts. The others looks like "trying too hard".

**Comment by campoy** [comment]
I love the first option of your latest comment, @ricardobaeta!
The other one is, as you say, going a bit too crazy for me haha.

**Comment by ricardobaeta** [comment]
Awesome @campoy !! Thanks!

How should we proceed in order for me to update the artwork repo? Do you perhaps know the specs and diversity of artwork assets we need?

**Comment by campoy** [comment]
The formats I'm thinking:

- sticker
- icon
- small logo on web pages
- HD for presentations on large screens

It's important to figure out what's the shape of the background too, though.
if you made it a sticker, would the white background be part of it? Maybe the bground should be black? That's up to you

**Comment by campoy** [comment]
So what happened to this, @ricardobaeta?

**Comment by ricardobaeta** [comment]
Hi @campoy ! I'll proceed with this pretty fast, sorry I didn't get back to you.

**Comment by campoy** [comment]
If you could provide a transparent background logo asap I could use it for my presentation.

**Comment by ricardobaeta** [comment]
Here it is @campoy !

![transparent-hd-for-presentations-on-large-screens](https://user-images.githubusercontent.com/1746146/44733604-d7d09480-aadf-11e8-8d58-bb348e9400da.png)

**Comment by ricardobaeta** [comment]
@campoy Really sorry for being late on this.

https://github.com/src-d/artwork/blob/master/pga/README.md
