### ISSUE TITLE
Provide md5 for index

### ISSUE THREAD

**Issue by campoy** [src-d/datasets#57]
Currently we provide md5 files for all siva files, but as far as I can tell, not for the index file itself.

Could we provide it on http://pga.sourced.tech/csv/latest.csv.gz.md5?

**Comment by bzz** [comment]
this should be able to address the concerns from #53

**Comment by campoy** [comment]
This would help with that issue, yes

**Comment by smola** [comment]
Maybe @rporres can generate it right in the server?

**Comment by rporres** [comment]
There you go! https://drive.google.com/file/d/1sVDBikw-L3FXj1VIICcNkuNId3C93xCk/view?usp=sharing

**Comment by bzz** [comment]
So cool! Let's include it in upcoming update with #66

**Comment by smola** [comment]
@campoy Is this fixed now?

**Comment by campoy** [comment]
Yes! 🎉
