### ISSUE TITLE
main issue tracker about PGA?

### ISSUE THREAD

**Issue by monperrus** [src-d/datasets#68]
Hi all,

Is that the correct issue tracker for questions & issues about PGA?

--Martin

**Comment by vmarkovtsev** [comment]
Hi, absolutely.

**Comment by bzz** [comment]
👍 

If no objections, going to close this as the question seems to be answered.

But please, feel free to re-open or open a new issue in case if something is not clear!

**Comment by monperrus** [comment]
Thanks! It may be a good idea to add a link to this issue tracker in 
https://blog.sourced.tech/post/announcing-pga/
or
https://pga.sourced.tech/
(or both!)
