### ISSUE TITLE
pga  get --stdin file.txt freezes

### ISSUE THREAD

**Issue by sakalouski** [src-d/datasets#82]
When I run **pga  get --stdin file.txt**, it freezes after the following messages: 

_downloading siva files by name from stdin
filter flags will be ignored_

even if there is only 1 siva file name in the file.txt.

**pga get -l python** works fine till some point (last time downloaded 10k repos), then freezes.
Tried decreasing number of workers to 1 - seemed to stabilize the process to some extent, but I still get this freeze. 

Any ideas?

**Comment by vmarkovtsev** [comment]
@campoy

**Comment by campoy** [comment]
Are you sending any content into `stdin`?
You should try `cat file.txt | pga get --stdin`.
