### ISSUE TITLE
"multitool" link broken on PGA page

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/datasets#83]
Although aware that there's an intention of removing pga.sourced.tech on [this issue](https://github.com/src-d/datasets/issues/76), we currently have a broken link there for `multitool` on:

> You can download and filter by csv data using [multitool](https://github.com/src-d/datasets/tree/master/PublicGitArchive/multitool).

I intended to fix it myself and push a PR but I could not find a new direction for `multitool` nor give a best solution for it, apart from removing this sentence. Guide me if I should fix it on [the html](https://github.com/src-d/datasets/blob/master/PublicGitArchive/web/web/index.html)

**Comment by vmarkovtsev** [comment]
No more `multitool` exists.
