### ISSUE TITLE
Warning using commands `pga list` or `pga get`

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/datasets#86]
When I tried to run `pga list --lang "Jupyter Notebook"` and `pga get --lang "Jupyter Notebook"` commands, I received before the proper response:

```
WARN[0000] could not check md5 hashes for http://pga.sourced.tech/csv/latest.csv.gz: could
not fetch hash at latest.csv.gz.md5: 404 Not Found
```

I have no idea what this means. Should I have done something to prevent this? Is this an error caused by something I did/didn't do, or a bug on PGA? I don't know.

**Comment by campoy** [comment]
This is not an error, just a warning, and I filed it long time ago with #57.

Any plans on when to fix it, @vmarkovtsev ?

**Comment by vmarkovtsev** [comment]
I am not a `pga` tool maintainer and Alex is no longer in Applications team, so double "no", I guess, @campoy.

**Comment by campoy** [comment]
This is not . a problem of the `pga` tool.
This is the lack of MD5 file available for the index.

The same way we have http://pga.sourced.tech/csv/latest.csv, we should have http://pga.sourced.tech/csv/latest.csv.gz.

**Comment by vmarkovtsev** [comment]
In any case Máximo wrote in DM yesterday that Data Retrieval are responsible for everything related.

**Comment by campoy** [comment]
Does that mean you're taking care of this issue and a hash for the index will be created, @vmarkovtsev ?

**Comment by vmarkovtsev** [comment]
@campoy I am not responsible for anything in PGA except maybe for some of the requirements and the data schema. That's data retrieval.

**Comment by campoy** [comment]
Hey @src-d/data-retrieval, can you take care of this?

**Comment by kuba--** [comment]
Really DR. Team is responsible for that? I've never heard that someone from DR worked on this, but maybe I'm wrong.

**Comment by vmarkovtsev** [comment]
Asking @smola to confirm

**Comment by smola** [comment]
@vmarkovtsev @campoy I cannot clarify this yet, but we'll do it as soon as possible.

Closing the issue as duplicate of https://github.com/src-d/datasets/issues/57

**Comment by kuba--** [comment]
Guys, this warning drives me crazy so much, so if no team is really responsible for that, I can take a look to fix it.

**Comment by smola** [comment]
@kuba-- I filed an infra request for this case, since it seems this will be fixed just by adding a md5sum file in the hosting server.

**Comment by bzz** [comment]
would be very nice to fix indeed

**Comment by kuba--** [comment]
Already fixed on master

**Comment by bzz** [comment]
🎉 linking for the history https://github.com/src-d/datasets/pull/88

**Comment by kuba--** [comment]
This is a question to _infra_ (@rporres / @meyskens)

**Comment by rporres** [comment]
Now in the TODO list
