### ISSUE TITLE
When would one repository contains more than one sivaFile?

### ISSUE THREAD

**Issue by ycaxgjd** [src-d/datasets#98]
Hey, I thought that one repo should have exactly one siva file until I found one repo which contains 5 different siva files, whose url is "https://github.com/pegasus-isi/pegasus". So, when would one repository contains more than one sivaFile?

**Comment by vmarkovtsev** [comment]
Hi @ycaxgjd 

We store git references with different roots in separate siva files. Refer to the [paper](https://arxiv.org/abs/1803.10144), page 2 "cloning git repositories".

**Comment by ycaxgjd** [comment]
Thanks!
